# Production stage
FROM nginx:latest 
RUN  ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY ./student  /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]