# 使用官方的 Node.js 镜像作为基础镜像
FROM node:12 AS build-stage

# 设置工作目录
WORKDIR /app

# 拷贝 package.json 和 package-lock.json 并安装依赖
COPY package*.json ./
RUN npm install

# 拷贝项目文件
COPY . .

# 打包 Vue.js 项目
RUN npm run build

# 使用 Nginx 作为基础镜像来部署 Vue.js 项目
FROM nginx:alpine

# 将构建好的 Vue.js 项目拷贝到 Nginx 静态文件目录
COPY --from=build-stage /app/student /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
# 暴露 80 端口
EXPOSE 80 

# 在容器启动时启动 Nginx 服务
CMD ["nginx", "-g", "daemon off;"]
